<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250903124724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE disponibilite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif VARCHAR(255) DEFAULT NULL, pilote_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2CBACE2FF510AAE9 ON disponibilite (pilote_id)');
        $this->addSql('CREATE INDEX idx_disponibilite_debut_fin ON disponibilite (debut, fin)');
        $this->addSql('CREATE INDEX idx_disponibilite_pilote_debut_fin ON disponibilite (pilote_id, debut, fin)');
        $this->addSql('ALTER TABLE disponibilite ADD CONSTRAINT FK_2CBACE2FF510AAE9 FOREIGN KEY (pilote_id) REFERENCES profil_pilote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client ADD use_availability_filter BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE profil_pilote ADD available_by_default BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE disponibilite DROP CONSTRAINT FK_2CBACE2FF510AAE9');
        $this->addSql('DROP TABLE disponibilite');
        $this->addSql('ALTER TABLE client DROP use_availability_filter');
        $this->addSql('ALTER TABLE profil_pilote DROP available_by_default');
    }
}
