<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250906155507 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, montant DOUBLE PRECISION DEFAULT NULL, beneficiaire VARCHAR(255) DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, mode VARCHAR(255) DEFAULT NULL, related_to_maintenance BOOLEAN DEFAULT NULL, document_id INT DEFAULT NULL, entretien_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D3A8DA6C33F7837 ON expense (document_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6548DCEA2 ON expense (entretien_id)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6C33F7837 FOREIGN KEY (document_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6548DCEA2 FOREIGN KEY (entretien_id) REFERENCES entretien (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client ADD has_expenses_management BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6C33F7837');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6548DCEA2');
        $this->addSql('DROP TABLE expense');
        $this->addSql('ALTER TABLE client DROP has_expenses_management');
    }
}
