<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250831070459 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profil_pilote_id INT DEFAULT NULL, aeronef_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_14D431325D6B9CC9 ON media_object (profil_pilote_id)');
        $this->addSql('CREATE INDEX IDX_14D43132BCB14BD8 ON media_object (aeronef_id)');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D431325D6B9CC9 FOREIGN KEY (profil_pilote_id) REFERENCES profil_pilote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132BCB14BD8 FOREIGN KEY (aeronef_id) REFERENCES aeronef (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE certificat_medical ADD document_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE certificat_medical ADD CONSTRAINT FK_3C705FDBC33F7837 FOREIGN KEY (document_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C705FDBC33F7837 ON certificat_medical (document_id)');
        $this->addSql('ALTER TABLE pilot_qualification ADD document_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pilot_qualification ADD CONSTRAINT FK_A9811BEEC33F7837 FOREIGN KEY (document_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9811BEEC33F7837 ON pilot_qualification (document_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE media_object DROP CONSTRAINT FK_14D431325D6B9CC9');
        $this->addSql('ALTER TABLE media_object DROP CONSTRAINT FK_14D43132BCB14BD8');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('ALTER TABLE pilot_qualification DROP CONSTRAINT FK_A9811BEEC33F7837');
        $this->addSql('DROP INDEX UNIQ_A9811BEEC33F7837');
        $this->addSql('ALTER TABLE pilot_qualification DROP document_id');
        $this->addSql('ALTER TABLE certificat_medical DROP CONSTRAINT FK_3C705FDBC33F7837');
        $this->addSql('DROP INDEX UNIQ_3C705FDBC33F7837');
        $this->addSql('ALTER TABLE certificat_medical DROP document_id');
    }
}
