<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250825034804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE carnet_vol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, aeronef VARCHAR(255) DEFAULT NULL, type_de_vol JSON NOT NULL, duree DOUBLE PRECISION NOT NULL, lieu_depart VARCHAR(255) DEFAULT NULL, lieu_arrivee VARCHAR(255) DEFAULT NULL, is_validated BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, profil_id INT DEFAULT NULL, created_by_id UUID DEFAULT NULL, updated_by_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96A66A5C275ED078 ON carnet_vol (profil_id)');
        $this->addSql('CREATE INDEX IDX_96A66A5CB03A8386 ON carnet_vol (created_by_id)');
        $this->addSql('CREATE INDEX IDX_96A66A5C896DBBDE ON carnet_vol (updated_by_id)');
        $this->addSql('ALTER TABLE carnet_vol ADD CONSTRAINT FK_96A66A5C275ED078 FOREIGN KEY (profil_id) REFERENCES profil_pilote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carnet_vol ADD CONSTRAINT FK_96A66A5CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carnet_vol ADD CONSTRAINT FK_96A66A5C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE carnet_vol DROP CONSTRAINT FK_96A66A5C275ED078');
        $this->addSql('ALTER TABLE carnet_vol DROP CONSTRAINT FK_96A66A5CB03A8386');
        $this->addSql('ALTER TABLE carnet_vol DROP CONSTRAINT FK_96A66A5C896DBBDE');
        $this->addSql('DROP TABLE carnet_vol');
    }
}
