<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250904054108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE airport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, main BOOLEAN DEFAULT NULL, meteo BOOLEAN DEFAULT NULL, client_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E91F7C219EB6921 ON airport (client_id)');
        $this->addSql('ALTER TABLE airport ADD CONSTRAINT FK_7E91F7C219EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_object ADD airport_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media_object ADD entretien_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132289F53C8 FOREIGN KEY (airport_id) REFERENCES airport (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132548DCEA2 FOREIGN KEY (entretien_id) REFERENCES entretien (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_14D43132289F53C8 ON media_object (airport_id)');
        $this->addSql('CREATE INDEX IDX_14D43132548DCEA2 ON media_object (entretien_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE airport DROP CONSTRAINT FK_7E91F7C219EB6921');
        $this->addSql('DROP TABLE airport');
        $this->addSql('ALTER TABLE media_object DROP CONSTRAINT FK_14D43132289F53C8');
        $this->addSql('ALTER TABLE media_object DROP CONSTRAINT FK_14D43132548DCEA2');
        $this->addSql('DROP INDEX IDX_14D43132289F53C8');
        $this->addSql('DROP INDEX IDX_14D43132548DCEA2');
        $this->addSql('ALTER TABLE media_object DROP airport_id');
        $this->addSql('ALTER TABLE media_object DROP entretien_id');
    }
}
